### ISSUE TITLE
Respect dex/str requirement

### ISSUE THREAD

**Issue by hellozyemlya** [UnresolvedExternal/Union_AlterDamage#1]
Can you please add configurable option to respect dex/str weapon requirement in damage calculation?
So, for example, all crossbows will have damage equals to damage+str and dex meele weapons will have (damage+dex)/10 * multiplier or something like that.

**Comment by UnresolvedExternal** [comment]
The plugin has been rewritten. The option is included. Release will be soon, I suppose...

**Comment by hellozyemlya** [comment]
@UnresolvedExternal thanks a lot for reply. Any chance to get unfinished source code right now? Or I need to be patient and wait for release?

**Comment by UnresolvedExternal** [comment]
@hellozyemlya done. Perhaps the project will remain unchanged.

**Comment by hellozyemlya** [comment]
Cool, thanks. Build from source and tested - works as intended. Closing this issue.
